server:
  servlet:
    context-path: /my-app
  port: 8085
spring:
  kafka:
    bootstrapAddress: localhost:9090
    groupId: group1
    topic: order_topic
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:store}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
logging:
  pattern:
     console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%mdc] %-5level %logger{40} - %msg%n'
  level:
    root: INFO
    org.springframework: INFO
    com.example.shop: DEBUG
app:
  kafka:
    enabled: true
  scheduling:
    enabled: false
    period: 10000
    percent: 0.1
  document:
    path: src/main/resources/reports
  interaction:
    rate:
      stub: false
  cache:
      expireAfterAccess: 60
service:
  path:
    url: http://localhost:8080/my-app


#      docker run -p 8888:8085 -e DATABASE_URL=jdbc:postgresql://host.docker.internal first-service


