server:
  servlet:
    context-path: /my-app
  port: 8085
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:product-store}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.shop: DEBUG
app:
  scheduling:
    enabled: false
    period: 10000
    percent: 0.1
  document:
    path: src/main/resources/reports
interaction:
  rate:
    stub: false

service:
  path:
    url: http://localhost:8080/my-app

#      docker run -p 8888:8085 -e DATABASE_URL=jdbc:postgresql://host.docker.internal first-service


