server:
  servlet:
    context-path: /my-app
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/product_store
    username: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.shop: DEBUG
app:
  scheduling:
      enabled: true
      period: 10000
      percent: 0.1
  document:
    path: src/main/resources/reports

